from typing import Any


class PreparedSmilesGraph:
    def __init__(self, data: object, /) -> None: ...

    @property
    def schema_version(self) -> int: ...

    @property
    def surface_kind(self) -> str: ...

    @property
    def policy_name(self) -> str: ...

    @property
    def policy_digest(self) -> str: ...

    @property
    def rdkit_version(self) -> str: ...

    @property
    def identity_smiles(self) -> str: ...

    @property
    def atom_count(self) -> int: ...

    @property
    def bond_count(self) -> int: ...

    @property
    def atom_tokens(self) -> list[str]: ...

    def neighbors_of(self, atom_idx: int, /) -> list[int]: ...
    def bond_token(self, begin_idx: int, end_idx: int, /) -> str: ...
    def validate_policy(self, policy_name: str, policy_digest: str, /) -> None: ...
    def enumerate_rooted_connected_nonstereo_support(self, root_idx: int, /) -> list[str]: ...
    def enumerate_rooted_connected_stereo_support(self, root_idx: int, /) -> list[str]: ...
    def to_dict(self) -> dict[str, Any]: ...


class RootedConnectedNonStereoWalkerState:
    @property
    def prefix(self) -> str: ...


class RootedConnectedNonStereoWalker:
    def __init__(self, graph: object, root_idx: int, /) -> None: ...

    @property
    def root_idx(self) -> int: ...

    def initial_state(self) -> RootedConnectedNonStereoWalkerState: ...
    def next_token_support(
        self,
        state: RootedConnectedNonStereoWalkerState,
        /,
    ) -> list[str]: ...
    def advance_token(
        self,
        state: RootedConnectedNonStereoWalkerState,
        chosen_token: str,
        /,
    ) -> RootedConnectedNonStereoWalkerState: ...
    def is_terminal(self, state: RootedConnectedNonStereoWalkerState, /) -> bool: ...
    def enumerate_support(self) -> list[str]: ...


class RootedConnectedStereoWalkerState:
    @property
    def prefix(self) -> str: ...


class RootedConnectedStereoWalker:
    def __init__(self, graph: object, root_idx: int, /) -> None: ...

    @property
    def root_idx(self) -> int: ...

    def initial_state(self) -> RootedConnectedStereoWalkerState: ...
    def next_token_support(
        self,
        state: RootedConnectedStereoWalkerState,
        /,
    ) -> list[str]: ...
    def advance_token(
        self,
        state: RootedConnectedStereoWalkerState,
        chosen_token: str,
        /,
    ) -> RootedConnectedStereoWalkerState: ...
    def is_terminal(self, state: RootedConnectedStereoWalkerState, /) -> bool: ...
    def enumerate_support(self) -> list[str]: ...


def prepared_smiles_graph_schema_version() -> int: ...
def mol_to_smiles_support(
    graph: object,
    root_idx: int,
    isomeric_smiles: bool,
    /,
) -> list[str]: ...
