"""RDKit-backed oracle, dataset, and artifact helpers.

This module is the intended Python entrypoint for reference-only behavior:
policy loading, dataset iteration, artifact generation, RDKit random sampling,
and the legacy pure-Python exact-support implementation used for parity tests.
"""

from smiles_next_token.reference import (
    DEFAULT_CORE_SELECTION_LIMIT,
    DEFAULT_MOLECULE_SOURCE_PATH,
    DEFAULT_RDKIT_RANDOM_CONNECTED_NONSTEREO_POLICY_PATH,
    DEFAULT_RDKIT_RANDOM_POLICY_PATH,
    CONNECTED_NONSTEREO_SURFACE,
    CONNECTED_STEREO_SURFACE,
    MoleculeCase,
    PREPARED_SMILES_GRAPH_SCHEMA_VERSION,
    PreparedSmilesGraph,
    RandomReferenceResult,
    REFERENCE_ARTIFACTS_ROOT,
    ReferencePolicy,
    RootedConnectedNonStereoWalker,
    RootedConnectedNonStereoWalkerState,
    ValidationIssue,
    build_core_exact_sets_artifact,
    build_full_metrics_artifact,
    enumerate_rooted_connected_nonstereo_smiles_support,
    enumerate_rooted_connected_stereo_smiles_support,
    enumerate_rooted_nonstereo_smiles_support,
    enumerate_rooted_smiles_support,
    iter_default_connected_nonstereo_molecule_cases,
    iter_default_molecule_cases,
    load_default_connected_nonstereo_molecule_cases,
    load_default_molecule_cases,
    molecule_has_stereochemistry,
    molecule_is_connected,
    prepare_smiles_graph,
    sample_and_validate_rdkit_random,
    sample_rdkit_random_smiles,
    sample_rdkit_random_smiles_from_root,
    validate_rooted_connected_nonstereo_smiles_support,
    validate_rooted_connected_stereo_smiles_support,
    validate_rooted_nonstereo_smiles_support,
    validate_rooted_smiles_support,
    write_core_exact_sets_artifact,
    write_full_metrics_artifact,
)

__all__ = [
    "DEFAULT_CORE_SELECTION_LIMIT",
    "DEFAULT_MOLECULE_SOURCE_PATH",
    "DEFAULT_RDKIT_RANDOM_CONNECTED_NONSTEREO_POLICY_PATH",
    "DEFAULT_RDKIT_RANDOM_POLICY_PATH",
    "CONNECTED_NONSTEREO_SURFACE",
    "CONNECTED_STEREO_SURFACE",
    "MoleculeCase",
    "PREPARED_SMILES_GRAPH_SCHEMA_VERSION",
    "PreparedSmilesGraph",
    "RandomReferenceResult",
    "REFERENCE_ARTIFACTS_ROOT",
    "ReferencePolicy",
    "RootedConnectedNonStereoWalker",
    "RootedConnectedNonStereoWalkerState",
    "ValidationIssue",
    "build_core_exact_sets_artifact",
    "build_full_metrics_artifact",
    "enumerate_rooted_connected_nonstereo_smiles_support",
    "enumerate_rooted_connected_stereo_smiles_support",
    "enumerate_rooted_nonstereo_smiles_support",
    "enumerate_rooted_smiles_support",
    "iter_default_connected_nonstereo_molecule_cases",
    "iter_default_molecule_cases",
    "load_default_connected_nonstereo_molecule_cases",
    "load_default_molecule_cases",
    "molecule_has_stereochemistry",
    "molecule_is_connected",
    "prepare_smiles_graph",
    "sample_and_validate_rdkit_random",
    "sample_rdkit_random_smiles",
    "sample_rdkit_random_smiles_from_root",
    "validate_rooted_connected_nonstereo_smiles_support",
    "validate_rooted_connected_stereo_smiles_support",
    "validate_rooted_nonstereo_smiles_support",
    "validate_rooted_smiles_support",
    "write_core_exact_sets_artifact",
    "write_full_metrics_artifact",
]
