"""Declarative default ordinary writer capability ledger."""

from __future__ import annotations

from grimace._south_star1.errors import SouthStarErrorKind

from tests.south_star1.default_writer_capability_contracts import (
    DEFAULT_OFFLINE_OBJECT_KINDS,
    DEFAULT_OFFLINE_RELATION_FAMILIES,
    DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
    DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    DISCONNECTED_OFFLINE_RELATION_FAMILIES,
    SUPPORT_SURFACE_DEFINITIONS,
    ContinuationProofExpectation,
    DefaultWriterCapabilityCase,
    QualificationAuthority,
    RdkitAuditFamily,
    accepted_writer_case,
    frontier_blocked_writer_case,
    preparation_blocked_writer_case,
    validate_default_writer_capability_contracts,
)

REMOTE_COUPLED_CONTINUATION_EXPECTATION = ContinuationProofExpectation(
    raw_cursor_count=3075,
    edge_locator_count=3074,
    branch_locator_count=3848,
    terminal_record_count=216,
    terminal_locator_count=216,
    replayed_operations=("tetrahedral atom-token restriction", "tetrahedral local-order factor closure"),
    checked_relation_families=(),
    checked_obligation_families=("graph_obligation_work", "residual_work", "stereo_lifecycle", "terminal_graph_obligation_work", "terminal_stereo_lifecycle"),
    unchecked_obligation_families=(),
)

DEFAULT_WRITER_CAPABILITY_CASES = (
    accepted_writer_case(
        name='ethanol',
        smiles='CCO',
        extraction_contract_id='ordinary_graph',
        support_surface='acyclic_graph',
        support_count=1,
        completion_count=1,
        support_digest='158da5592968f7fdda045dd00edb2fa2efa66ce320dc29cb4c95c1a03a918a7d',
    ),
    accepted_writer_case(
        name='branched_alcohol',
        smiles='CC(C)O',
        extraction_contract_id='ordinary_graph',
        support_surface='branched_graph',
        support_count=2,
        completion_count=2,
        support_digest='b8b02b860ced5a1bbf327d50859b9ce3b7565a9d1a7bce8d0165c8178a7112b8',
    ),
    accepted_writer_case(
        name='cyclopropane',
        smiles='C1CC1',
        extraction_contract_id='ordinary_graph',
        support_surface='single_ring_closure',
        support_count=1,
        completion_count=2,
        support_digest='312276a2ad4cdc05fe8ad6b024ada99af6fb832b8d02414ec769ae85b286decd',
    ),
    accepted_writer_case(
        name='cyclobutane',
        smiles='C1CCC1',
        extraction_contract_id='ordinary_graph',
        support_surface='single_ring_closure',
        support_count=1,
        completion_count=2,
        support_digest='a6905e29e645f4d04479ce90a41a3bb276baba14bba3fc36d6f83e2dc61d6d17',
    ),
    accepted_writer_case(
        name='cyclopropene_double_closure',
        smiles='C1=CC1',
        extraction_contract_id='ordinary_graph',
        support_surface='non_single_ring_closure_double',
        support_count=3,
        completion_count=3,
        support_digest='8e6083dc9807cd94031fbae1a9cf9e7d85efc7f8450a017fd22e95c3a46cf836',
    ),
    accepted_writer_case(
        name='cyclopropyne_triple_closure',
        smiles='C1#CC1',
        extraction_contract_id='ordinary_graph',
        support_surface='non_single_ring_closure_triple',
        support_count=3,
        completion_count=3,
        support_digest='7aa9e14f4a2340677cbb14f2281aac8e4fed116870899c72cd5b910e1d7a4695',
    ),
    accepted_writer_case(
        name='branched_cyclobutane',
        smiles='C1CC(C)C1',
        extraction_contract_id='ordinary_graph',
        support_surface='branched_ring',
        support_count=2,
        completion_count=4,
        support_digest='ea98a1e3ebec1a69635db0d3bafb2df37ac59eb78aa5660602cf2c4d8150966d',
    ),
    accepted_writer_case(
        name='nitrogen_cation',
        smiles='[N+]',
        extraction_contract_id='ordinary_graph',
        support_surface='simple_bracket_charge',
        support_count=1,
        completion_count=1,
        support_digest='3e0dafe1d624e7e97c5d7b691949ffa7c22306a7e95bf47680d71550d0292b0d',
    ),
    accepted_writer_case(
        name='iminium_hydrogen_cation',
        smiles='[NH+]',
        extraction_contract_id='ordinary_graph',
        support_surface='simple_bracket_charge',
        support_count=1,
        completion_count=1,
        support_digest='8f26d7dc968fc63177d76b06157a835c75480cd7b0f4271c6a77b1dfcc9b98b6',
    ),
    accepted_writer_case(
        name='amino_cation',
        smiles='[NH2+]',
        extraction_contract_id='ordinary_graph',
        support_surface='simple_bracket_charge',
        support_count=1,
        completion_count=1,
        support_digest='4da0d2d64ad0649366cfa81a3994fec9589bc4e249a806707784d704d956c591',
    ),
    accepted_writer_case(
        name='ammonia_cation',
        smiles='[NH3+]',
        extraction_contract_id='ordinary_graph',
        support_surface='simple_bracket_charge',
        support_count=1,
        completion_count=1,
        support_digest='ae9db23fc1587d0c8634d031ebdfaafdea0a8a3e6af1dae1183f2c71c67b1391',
    ),
    accepted_writer_case(
        name='ammonium_charge',
        smiles='[NH4+]',
        extraction_contract_id='ordinary_graph',
        support_surface='simple_bracket_charge',
        support_count=1,
        completion_count=1,
        support_digest='7ecb28fb094c1b9013610ebb987e39e8b76e55bfdb38af53ab682bd2f1467719',
    ),
    accepted_writer_case(
        name='oxide_anion',
        smiles='[O-]',
        extraction_contract_id='ordinary_graph',
        support_surface='simple_bracket_charge',
        support_count=1,
        completion_count=1,
        support_digest='bfa4c3013b04f7db71e834923cce839e0499c9d702fb2e704fd4e13c9ad189bb',
    ),
    accepted_writer_case(
        name='hydroxide_anion',
        smiles='[OH-]',
        extraction_contract_id='ordinary_graph',
        support_surface='simple_bracket_charge',
        support_count=1,
        completion_count=1,
        support_digest='4ce4a6fbb41bf1f00917e46cb5164119c2a52990305cd4888ff8a7fc621df10f',
    ),
    accepted_writer_case(
        name='isotopic_methane',
        smiles='[13CH4]',
        extraction_contract_id='ordinary_graph',
        support_surface='simple_isotope_bracket_atom',
        support_count=1,
        completion_count=1,
        support_digest='28b7468eeb6985fb4cb5d56ab6f665c9d3fb65d63519f625668f797d18b61242',
    ),
    accepted_writer_case(
        name='zero_h_tetrahedral',
        smiles='C[C@](F)(Cl)Br',
        extraction_contract_id='ordinary_coupled_tetrahedral_stereo',
        support_surface='specified_tetrahedral_zero_h',
        support_count=24,
        completion_count=24,
        support_digest='ba947a23b358660cbd77689f5f60be8f1cc4a069f0e543bccee8955f3b9fcacb',
        rooted_at_atom=1,
    ),
    accepted_writer_case(
        name='adjacent_specified_tetrahedral',
        smiles='[C@H](F)(Cl)[C@@](F)(Cl)Br',
        extraction_contract_id='ordinary_coupled_tetrahedral_stereo',
        support_surface='specified_tetrahedral_adjacent',
        support_count=36,
        completion_count=36,
        support_digest='1c0cfb5a125fb9c8685d6d18c9bebb0fb0569fcf8411bceb4d7219b3a525a8a9',
    ),
    accepted_writer_case(
        name='remote_coupled_tetrahedral_a',
        smiles='[C@H](F)([C@](F)(Cl)Br)[C@@](F)(Cl)Br',
        extraction_contract_id='ordinary_coupled_tetrahedral_stereo',
        support_surface='specified_tetrahedral_coupled',
        support_count=216,
        completion_count=216,
        support_digest='9fd3f7a1b862f6fadc534098c61c072448a7aa70b45ffadc4257bbe2dac70533',
        qualification_authority="continuation_proof_complete",
        continuation=REMOTE_COUPLED_CONTINUATION_EXPECTATION,
    ),
    accepted_writer_case(
        name='remote_coupled_tetrahedral_b',
        smiles='[C@@H](F)([C@](F)(Cl)Br)[C@@](F)(Cl)Br',
        extraction_contract_id='ordinary_coupled_tetrahedral_stereo',
        support_surface='specified_tetrahedral_coupled',
        support_count=216,
        completion_count=216,
        support_digest='0e16f5133e74556aeebc06817368c7e7e377672bcbcf2827d9285417eb3c8094',
        qualification_authority="continuation_proof_complete",
        continuation=REMOTE_COUPLED_CONTINUATION_EXPECTATION,
    ),
    accepted_writer_case(
        name='tetra_plus',
        smiles='[C@H](F)(Cl)Br',
        extraction_contract_id='ordinary_specified_stereo',
        support_surface='specified_tetrahedral',
        support_count=6,
        completion_count=6,
        support_digest='216234e0ae01eef57744222590d56573b8e0c9f92e27dac0653b0372db4dae14',
    ),
    accepted_writer_case(
        name='tetra_minus',
        smiles='[C@@H](F)(Cl)Br',
        extraction_contract_id='ordinary_specified_stereo',
        support_surface='specified_tetrahedral',
        support_count=6,
        completion_count=6,
        support_digest='61c45f124f99413fb8d8e32612acc7a9c027fc6d372c133cb7a6b9b22585035f',
    ),
    accepted_writer_case(
        name='directional_opposite',
        smiles='F/C=C/Cl',
        extraction_contract_id='ordinary_specified_stereo',
        support_surface='specified_directional_acyclic_implicit_h',
        support_count=2,
        completion_count=2,
        support_digest='3f8f9edb2af9ff8964fa04e8ba6b8374177e773cceea2f1959cc27026bed7595',
    ),
    accepted_writer_case(
        name='directional_together',
        smiles='F/C=C\\Cl',
        extraction_contract_id='ordinary_specified_stereo',
        support_surface='specified_directional_acyclic_implicit_h',
        support_count=2,
        completion_count=2,
        support_digest='a5ad275c56e9dfc9530d7985fc85428997509701c95e0c2f1249a01a9d103fd8',
    ),
    accepted_writer_case(
        name='disconnected_cc_oxygen',
        smiles='CC.O',
        extraction_contract_id='ordinary_graph',
        support_surface='disconnected_fixed_order',
        support_count=1,
        completion_count=1,
        support_digest='c496d6252cbc6b43f8c55f0e55236a819b63685c7daf27d3886efb521bb938f4',
    ),
    accepted_writer_case(
        name='disconnected_oxygen_cc',
        smiles='O.CC',
        extraction_contract_id='ordinary_graph',
        support_surface='disconnected_fixed_order',
        support_count=1,
        completion_count=1,
        support_digest='e8a7fe0505c836a927826a8adbc6537301bedd7f999552116c84a02d4e237d14',
        rooted_at_atom=1,
    ),
    accepted_writer_case(
        name='disconnected_duplicate_ethanes',
        smiles='CC.CC',
        extraction_contract_id='ordinary_graph',
        support_surface='disconnected_fixed_order',
        support_count=1,
        completion_count=2,
        support_digest='7f58112ef003c228917c772afc45ce6090908fba07cc7104692a7344228a7c9b',
    ),
    accepted_writer_case(
        name='disconnected_ring_oxygen',
        smiles='C1CC1.O',
        extraction_contract_id='ordinary_graph',
        support_surface='disconnected_fixed_order',
        support_count=1,
        completion_count=2,
        support_digest='45163fc5fa812e667d8989f5ddcb7bf486ca4df0f1c80634397015b6472cc144',
    ),
    accepted_writer_case(
        name='disconnected_ammonium_cyanide',
        smiles='[NH4+].C#N',
        extraction_contract_id='ordinary_graph',
        support_surface='disconnected_fixed_order',
        support_count=2,
        completion_count=2,
        support_digest='4b55dc94da4ae4cfd3eaec167320cc374ef9caec3ef4ff287e2eab7b9cd11d82',
    ),
    accepted_writer_case(
        name='disconnected_tetra_oxygen',
        smiles='[C@H](F)(Cl)Br.O',
        extraction_contract_id='ordinary_specified_stereo',
        support_surface='disconnected_fixed_order',
        support_count=6,
        completion_count=6,
        support_digest='55227adff1bf5af672a91ff730e73e2aa954c978bd6f9cbd9593f659182a50f5',
    ),
    accepted_writer_case(
        name='disconnected_directional_oxygen',
        smiles='F/C=C/Cl.O',
        extraction_contract_id='ordinary_specified_stereo',
        support_surface='disconnected_fixed_order',
        support_count=2,
        completion_count=2,
        support_digest='332671b292810b0434c3678f05b542ea3c35be6f18ee1f20209d23b59cbd013f',
    ),
    accepted_writer_case(
        name='aromatic_benzene',
        smiles='c1ccccc1',
        extraction_contract_id='ordinary_graph',
        support_surface='aromatic_homocycle',
        support_count=1,
        completion_count=2,
        support_digest='226af40c047f4e9f24f5c075b5cb84d44fbe96d5c0b60ae8d87552a477fd1990',
    ),
    accepted_writer_case(
        name='aromatic_pyridine',
        smiles='n1ccccc1',
        extraction_contract_id='ordinary_graph',
        support_surface='aromatic_heterocycle',
        support_count=1,
        completion_count=2,
        support_digest='661ae93b36570c6b2ee32fd0221d74b9227731a0c0fdd9f2aa77ce5e3bf8a1a7',
    ),
    accepted_writer_case(
        name='aromatic_furan',
        smiles='c1occc1',
        extraction_contract_id='ordinary_graph',
        support_surface='aromatic_heterocycle',
        support_count=2,
        completion_count=2,
        support_digest='804c1bbdde3d104e192df9c348cc9718cef782236a1e53b3152e299d2351d496',
    ),
    accepted_writer_case(
        name='aromatic_thiophene',
        smiles='c1sccc1',
        extraction_contract_id='ordinary_graph',
        support_surface='aromatic_heterocycle',
        support_count=2,
        completion_count=2,
        support_digest='e1ed422e051f2cd58b0badd0271d63ea88a0069a7ad0ac7a3595e1d1f9590e2a',
    ),
    accepted_writer_case(
        name='aromatic_naphthalene',
        smiles='c1ccc2ccccc2c1',
        extraction_contract_id='ordinary_graph',
        support_surface='fused_aromatic',
        support_count=6,
        completion_count=6,
        support_digest='77bca9da5f7996678315e2cc687dc1286d2a31f8971f671eae36bb615932627c',
    ),
    accepted_writer_case(
        name='aromatic_toluene',
        smiles='Cc1ccccc1',
        extraction_contract_id='ordinary_graph',
        support_surface='aromatic_substitution',
        support_count=1,
        completion_count=2,
        support_digest='f443887e18b3a8b7abd9d4361980c0765c68c34ef03017967153e02f5fbae315',
    ),
    accepted_writer_case(
        name='aromatic_biphenyl',
        smiles='c1ccccc1-c1ccccc1',
        extraction_contract_id='ordinary_graph',
        support_surface='aromatic_single_bridge',
        support_count=3,
        completion_count=6,
        support_digest='5409e73cdaec32ad944918ee327c941ba33c227f37bceb10160327c3872e9396',
    ),
    accepted_writer_case(
        name='aromatic_disconnected_benzene',
        smiles='c1ccccc1.O',
        extraction_contract_id='ordinary_graph',
        support_surface='disconnected_aromatic',
        support_count=1,
        completion_count=2,
        support_digest='598ab02d6998a35fec5e8865881cb3d2756cacec891ef260a317f55e2d8c0e96',
    ),
    preparation_blocked_writer_case(
        name='aromatic_bracketed_nh_boundary',
        smiles='[nH]1cccc1',
        extraction_contract_id='ordinary_graph',
        support_surface='unsupported_aromatic_bracketed_hydrogen',
        kind='unsupported_atom',
        error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        message_contains='[nH] atoms are unsupported',
    ),
    preparation_blocked_writer_case(
        name='aromatic_boron_boundary',
        smiles='b1ccccc1',
        extraction_contract_id='ordinary_graph',
        support_surface='unsupported_aromatic_boron',
        kind='unsupported_atom',
        error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        message_contains="aromatic spelling is unsupported for 'B'",
    ),
    preparation_blocked_writer_case(
        name='aromatic_phosphorus_boundary',
        smiles='p1ccccc1',
        extraction_contract_id='ordinary_graph',
        support_surface='unsupported_aromatic_phosphorus',
        kind='unsupported_atom',
        error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        message_contains="aromatic spelling is unsupported for 'P'",
    ),
    preparation_blocked_writer_case(
        name='aromatic_atom_map_boundary',
        smiles='c1cc[c:1]cc1',
        extraction_contract_id='ordinary_graph',
        support_surface='unsupported_aromatic_atom_map',
        kind='unsupported_atom',
        error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        message_contains='atom-mapped ordinary ingestion is unsupported',
    ),
    preparation_blocked_writer_case(
        name='charged_isotope_methyl',
        smiles='[13CH3+]',
        extraction_contract_id='ordinary_graph',
        support_surface='unsupported_charged_isotope',
        kind='unsupported_atom',
        error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        message_contains='isotopic atoms are unsupported',
    ),
    preparation_blocked_writer_case(
        name='oxygen_positive_charge',
        smiles='[O+]',
        extraction_contract_id='ordinary_graph',
        support_surface='unsupported_positive_oxygen_charge',
        kind='unsupported_atom',
        error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        message_contains='charged atoms are unsupported',
    ),
    preparation_blocked_writer_case(
        name='nitrogen_negative_charge',
        smiles='[NH2-]',
        extraction_contract_id='ordinary_graph',
        support_surface='unsupported_negative_nitrogen_charge',
        kind='unsupported_atom',
        error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        message_contains='charged atoms are unsupported',
    ),
    preparation_blocked_writer_case(
        name='oxygen_charged_isotope',
        smiles='[18OH-]',
        extraction_contract_id='ordinary_graph',
        support_surface='unsupported_charged_oxygen_isotope',
        kind='unsupported_atom',
        error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        message_contains='isotopic atoms are unsupported',
    ),
    frontier_blocked_writer_case(
        name='cyclopropene_potential_directional_boundary',
        smiles='C1=CC1',
        extraction_contract_id='ordinary_potential_stereo',
        support_surface='unsupported_potential_directional_non_neighbor',
        kind='unsupported_directional_non_neighbor_ligand',
        operation='directional carrier-mark restriction',
    ),
)

ACCEPTED_DEFAULT_WRITER_CAPABILITY_CASES = tuple(item for item in DEFAULT_WRITER_CAPABILITY_CASES if item.expected == "accepted")
BLOCKED_DEFAULT_WRITER_CAPABILITY_CASES = tuple(item for item in DEFAULT_WRITER_CAPABILITY_CASES if item.expected == "blocked")
DEFAULT_WRITER_CAPABILITY_CASES_BY_NAME = {item.name: item for item in DEFAULT_WRITER_CAPABILITY_CASES}

def default_writer_capability_case(name: str) -> DefaultWriterCapabilityCase:
    try: return DEFAULT_WRITER_CAPABILITY_CASES_BY_NAME[name]
    except KeyError as error: raise ValueError(f"unknown default writer capability case: {name!r}") from error

def default_writer_cases_for_rdkit_audit(family: RdkitAuditFamily) -> tuple[DefaultWriterCapabilityCase, ...]:
    if family not in {"aromatic", "bracket", "disconnected", "stereo"}: raise ValueError(f"unknown RDKit audit family: {family!r}")
    return tuple(case for case in DEFAULT_WRITER_CAPABILITY_CASES if family in case.rdkit_audit_families)

def validate_default_writer_capability_ledger() -> None:
    validate_default_writer_capability_contracts()
    names = tuple(case.name for case in DEFAULT_WRITER_CAPABILITY_CASES)
    if len(names) != len(set(names)) or set(DEFAULT_WRITER_CAPABILITY_CASES_BY_NAME) != set(names): raise ValueError("case name index is incomplete or non-unique")
    surfaces = {item.name for item in SUPPORT_SURFACE_DEFINITIONS}
    if {case.support_surface for case in DEFAULT_WRITER_CAPABILITY_CASES} != surfaces: raise ValueError("registered support surface is unused")
    for case in DEFAULT_WRITER_CAPABILITY_CASES:
        surface = next(item for item in SUPPORT_SURFACE_DEFINITIONS if item.name == case.support_surface)
        if case.expected == "accepted":
            if surface.expected_disposition != "accepted" or case.expected_support_count is None or case.expected_completion_count is None or case.expected_support_digest is None: raise ValueError(f"invalid accepted case: {case.name}")
            if case.qualification_authority == "continuation_proof_complete" and case.expected_continuation_raw_cursor_count is None: raise ValueError(f"missing continuation expectation: {case.name}")
            if case.qualification_authority == "materialized_support_artifact" and case.expected_continuation_raw_cursor_count is not None: raise ValueError(f"unexpected continuation expectation: {case.name}")
        elif surface.expected_disposition != "blocked" or case.expected_support_count is not None or case.blocker_phase is None: raise ValueError(f"invalid blocked case: {case.name}")
    a=DEFAULT_WRITER_CAPABILITY_CASES_BY_NAME["remote_coupled_tetrahedral_a"]; b=DEFAULT_WRITER_CAPABILITY_CASES_BY_NAME["remote_coupled_tetrahedral_b"]
    if a.expected_continuation_replayed_operations is not b.expected_continuation_replayed_operations: raise ValueError("remote continuation expectation is not shared")

__all__ = (
    "ACCEPTED_DEFAULT_WRITER_CAPABILITY_CASES", "BLOCKED_DEFAULT_WRITER_CAPABILITY_CASES",
    "DEFAULT_OFFLINE_OBJECT_KINDS", "DEFAULT_OFFLINE_RELATION_FAMILIES", "DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS", "DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES",
    "DEFAULT_WRITER_CAPABILITY_CASES", "DEFAULT_WRITER_CAPABILITY_CASES_BY_NAME", "DefaultWriterCapabilityCase", "DISCONNECTED_OFFLINE_RELATION_FAMILIES", "QualificationAuthority",
    "REMOTE_COUPLED_CONTINUATION_EXPECTATION", "default_writer_capability_case", "default_writer_cases_for_rdkit_audit", "validate_default_writer_capability_ledger",
 )
