"""Declared default ordinary writer capability ledger for South Star tests."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from grimace._south_star1.errors import SouthStarErrorKind
from grimace._south_star1.rdkit_adapter import RdkitOrdinaryExtractionOptions
from grimace._south_star1.ordinary_stereo_sites import OrdinaryStereoSiteOptions


_GRAPH_EXTRACTION = RdkitOrdinaryExtractionOptions(include_potential_sites=False)
_POTENTIAL_STEREO_EXTRACTION = RdkitOrdinaryExtractionOptions(
    include_potential_sites=True,
)
_SPECIFIED_STEREO_EXTRACTION = RdkitOrdinaryExtractionOptions(
    include_potential_sites=True,
    stereo_site_discovery_mode="specified_closure",
)
_COUPLED_TETRA_EXTRACTION = RdkitOrdinaryExtractionOptions(
    include_potential_sites=True,
    stereo_site_discovery_mode="specified_closure",
    stereo_site_options=OrdinaryStereoSiteOptions(
        ligand_equivalence="exact_stereochemical_graph_automorphism",
    ),
)

DEFAULT_OFFLINE_RELATION_FAMILIES = (
    "branch_projection_identity",
    "count_dag_arithmetic",
    "graph_ring_branch_delta",
    "local_branch_successor_evidence",
    "residual_stereo_obligation_classification",
    "support_image_coverage",
    "support_string_replay_path",
    "terminal_support_identity",
)
DISCONNECTED_OFFLINE_RELATION_FAMILIES = (
    *DEFAULT_OFFLINE_RELATION_FAMILIES,
    "component_boundary_transition",
)

DEFAULT_OFFLINE_OBJECT_KINDS = (
    "branch_support",
    "count_dag",
    "count_envelope",
    "frontier_product",
    "replay_path",
    "source_snapshot",
    "support_image",
    "support_image_coverage",
    "support_string",
    "terminal_projection",
    "terminal_support",
    "text_projection",
)

DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS: tuple[str, ...] = ()
DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES: tuple[str, ...] = ()

DEFAULT_ACCEPTED_AGREEMENT_TIERS = {
    "expected_live_frontier_agreement_complete": True,
    "expected_live_count_agreement_complete": True,
    "expected_snapshot_resume_agreement_complete": True,
    "expected_continuation_asset_complete": True,
    "expected_rust_runtime_agreement_complete": True,
    "expected_continuation_snapshot_resume_complete": True,
    "expected_lazy_branch_proof_complete": True,
    "expected_lazy_terminal_proof_complete": True,
}

QualificationAuthority = Literal[
    "materialized_support_artifact",
    "continuation_proof_complete",
]

REMOTE_COUPLED_CONTINUATION_REPLAYED_OPERATIONS = (
    "tetrahedral atom-token restriction",
    "tetrahedral local-order factor closure",
)
REMOTE_COUPLED_CONTINUATION_CHECKED_RELATION_FAMILIES: tuple[str, ...] = ()
REMOTE_COUPLED_CONTINUATION_CHECKED_OBLIGATION_FAMILIES = (
    "graph_obligation_work",
    "residual_work",
    "stereo_lifecycle",
    "terminal_graph_obligation_work",
    "terminal_stereo_lifecycle",
)
REMOTE_COUPLED_CONTINUATION_UNCHECKED_OBLIGATION_FAMILIES: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class DefaultWriterCapabilityCase:
    name: str
    smiles: str
    extraction_profile: Literal[
        "graph_no_potential_sites",
        "specified_stereo_closure",
        "with_potential_sites",
    ]
    extraction_options: RdkitOrdinaryExtractionOptions
    expected: Literal["accepted", "blocked"]
    support_surface: str
    qualification_authority: QualificationAuthority | None = "materialized_support_artifact"
    rooted_at_atom: int = 0
    expected_support_count: int | None = None
    expected_completion_count: int | None = None
    blocker_phase: Literal["preparation", "frontier"] | None = None
    blocker_kind: str | None = None
    blocker_operation: str | None = None
    blocker_error_kind: SouthStarErrorKind | None = None
    blocker_message_contains: str | None = None
    expected_structural_artifact: bool = False
    expected_live_artifact_verifier: bool = False
    expected_facts_bound_verifier: bool = False
    expected_offline_replay_complete: bool = False
    expected_live_frontier_agreement_complete: bool = False
    expected_live_count_agreement_complete: bool = False
    expected_snapshot_resume_agreement_complete: bool = False
    expected_continuation_asset_complete: bool = False
    expected_rust_runtime_agreement_complete: bool = False
    expected_continuation_snapshot_resume_complete: bool = False
    expected_lazy_branch_proof_complete: bool = False
    expected_lazy_terminal_proof_complete: bool = False
    expected_support_digest: str | None = None
    expected_rdkit_audit_version_pinned: bool = False
    expected_offline_object_kinds: tuple[str, ...] = ()
    expected_offline_unchecked_object_kinds: tuple[str, ...] = ()
    expected_offline_relation_families: tuple[str, ...] = ()
    expected_offline_unchecked_obligation_families: tuple[str, ...] = ()
    expected_continuation_raw_cursor_count: int | None = None
    expected_continuation_edge_locator_count: int | None = None
    expected_continuation_branch_locator_count: int | None = None
    expected_continuation_terminal_record_count: int | None = None
    expected_continuation_terminal_locator_count: int | None = None
    expected_continuation_replayed_operations: tuple[str, ...] = ()
    expected_continuation_checked_relation_families: tuple[str, ...] = ()
    expected_continuation_checked_obligation_families: tuple[str, ...] = ()
    expected_continuation_unchecked_obligation_families: tuple[str, ...] = ()


def _accepted_aromatic_case(
    *,
    name: str,
    smiles: str,
    support_surface: str,
    support_count: int,
    completion_count: int,
    support_digest: str,
    disconnected: bool = False,
) -> DefaultWriterCapabilityCase:
    return DefaultWriterCapabilityCase(
        name=name,
        smiles=smiles,
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface=support_surface,
        expected_support_count=support_count,
        expected_completion_count=completion_count,
        expected_support_digest=support_digest,
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        expected_rdkit_audit_version_pinned=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=(
            DISCONNECTED_OFFLINE_RELATION_FAMILIES
            if disconnected
            else DEFAULT_OFFLINE_RELATION_FAMILIES
        ),
    )


DEFAULT_WRITER_CAPABILITY_CASES = (
    DefaultWriterCapabilityCase(
        name="ethanol",
        smiles="CCO",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="acyclic_graph",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="158da5592968f7fdda045dd00edb2fa2efa66ce320dc29cb4c95c1a03a918a7d",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="branched_alcohol",
        smiles="CC(C)O",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="branched_graph",
        expected_support_count=2,
        expected_completion_count=2,
        expected_support_digest="b8b02b860ced5a1bbf327d50859b9ce3b7565a9d1a7bce8d0165c8178a7112b8",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="cyclopropane",
        smiles="C1CC1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="single_ring_closure",
        expected_support_count=1,
        expected_completion_count=2,
        expected_support_digest="312276a2ad4cdc05fe8ad6b024ada99af6fb832b8d02414ec769ae85b286decd",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="cyclobutane",
        smiles="C1CCC1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="single_ring_closure",
        expected_support_count=1,
        expected_completion_count=2,
        expected_support_digest="a6905e29e645f4d04479ce90a41a3bb276baba14bba3fc36d6f83e2dc61d6d17",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="cyclopropene_double_closure",
        smiles="C1=CC1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="non_single_ring_closure_double",
        expected_support_count=3,
        expected_completion_count=3,
        expected_support_digest="8e6083dc9807cd94031fbae1a9cf9e7d85efc7f8450a017fd22e95c3a46cf836",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="cyclopropyne_triple_closure",
        smiles="C1#CC1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="non_single_ring_closure_triple",
        expected_support_count=3,
        expected_completion_count=3,
        expected_support_digest="7aa9e14f4a2340677cbb14f2281aac8e4fed116870899c72cd5b910e1d7a4695",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="branched_cyclobutane",
        smiles="C1CC(C)C1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="branched_ring",
        expected_support_count=2,
        expected_completion_count=4,
        expected_support_digest="ea98a1e3ebec1a69635db0d3bafb2df37ac59eb78aa5660602cf2c4d8150966d",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="nitrogen_cation",
        smiles="[N+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="3e0dafe1d624e7e97c5d7b691949ffa7c22306a7e95bf47680d71550d0292b0d",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="iminium_hydrogen_cation",
        smiles="[NH+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="8f26d7dc968fc63177d76b06157a835c75480cd7b0f4271c6a77b1dfcc9b98b6",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="amino_cation",
        smiles="[NH2+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="4da0d2d64ad0649366cfa81a3994fec9589bc4e249a806707784d704d956c591",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="ammonia_cation",
        smiles="[NH3+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="ae9db23fc1587d0c8634d031ebdfaafdea0a8a3e6af1dae1183f2c71c67b1391",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="ammonium_charge",
        smiles="[NH4+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="7ecb28fb094c1b9013610ebb987e39e8b76e55bfdb38af53ab682bd2f1467719",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="oxide_anion",
        smiles="[O-]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="bfa4c3013b04f7db71e834923cce839e0499c9d702fb2e704fd4e13c9ad189bb",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="hydroxide_anion",
        smiles="[OH-]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="4ce4a6fbb41bf1f00917e46cb5164119c2a52990305cd4888ff8a7fc621df10f",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="isotopic_methane",
        smiles="[13CH4]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_isotope_bracket_atom",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="28b7468eeb6985fb4cb5d56ab6f665c9d3fb65d63519f625668f797d18b61242",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="zero_h_tetrahedral",
        smiles="C[C@](F)(Cl)Br",
        extraction_profile="specified_stereo_closure",
        extraction_options=_COUPLED_TETRA_EXTRACTION,
        expected="accepted",
        support_surface="specified_tetrahedral_zero_h",
        rooted_at_atom=1,
        expected_support_count=24,
        expected_completion_count=24,
        expected_support_digest="ba947a23b358660cbd77689f5f60be8f1cc4a069f0e543bccee8955f3b9fcacb",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="adjacent_specified_tetrahedral",
        smiles="[C@H](F)(Cl)[C@@](F)(Cl)Br",
        extraction_profile="specified_stereo_closure",
        extraction_options=_COUPLED_TETRA_EXTRACTION,
        expected="accepted",
        support_surface="specified_tetrahedral_adjacent",
        expected_support_count=36,
        expected_completion_count=36,
        expected_support_digest="1c0cfb5a125fb9c8685d6d18c9bebb0fb0569fcf8411bceb4d7219b3a525a8a9",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="remote_coupled_tetrahedral_a",
        smiles="[C@H](F)([C@](F)(Cl)Br)[C@@](F)(Cl)Br",
        extraction_profile="specified_stereo_closure",
        extraction_options=_COUPLED_TETRA_EXTRACTION,
        expected="accepted",
        support_surface="specified_tetrahedral_coupled",
        qualification_authority="continuation_proof_complete",
        expected_support_count=216,
        expected_completion_count=216,
        expected_support_digest="9fd3f7a1b862f6fadc534098c61c072448a7aa70b45ffadc4257bbe2dac70533",
        expected_continuation_raw_cursor_count=3075,
        expected_continuation_edge_locator_count=3074,
        expected_continuation_branch_locator_count=3848,
        expected_continuation_terminal_record_count=216,
        expected_continuation_terminal_locator_count=216,
        expected_continuation_replayed_operations=REMOTE_COUPLED_CONTINUATION_REPLAYED_OPERATIONS,
        expected_continuation_checked_relation_families=REMOTE_COUPLED_CONTINUATION_CHECKED_RELATION_FAMILIES,
        expected_continuation_checked_obligation_families=REMOTE_COUPLED_CONTINUATION_CHECKED_OBLIGATION_FAMILIES,
        expected_continuation_unchecked_obligation_families=REMOTE_COUPLED_CONTINUATION_UNCHECKED_OBLIGATION_FAMILIES,
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="remote_coupled_tetrahedral_b",
        smiles="[C@@H](F)([C@](F)(Cl)Br)[C@@](F)(Cl)Br",
        extraction_profile="specified_stereo_closure",
        extraction_options=_COUPLED_TETRA_EXTRACTION,
        expected="accepted",
        support_surface="specified_tetrahedral_coupled",
        qualification_authority="continuation_proof_complete",
        expected_support_count=216,
        expected_completion_count=216,
        expected_support_digest="0e16f5133e74556aeebc06817368c7e7e377672bcbcf2827d9285417eb3c8094",
        expected_continuation_raw_cursor_count=3075,
        expected_continuation_edge_locator_count=3074,
        expected_continuation_branch_locator_count=3848,
        expected_continuation_terminal_record_count=216,
        expected_continuation_terminal_locator_count=216,
        expected_continuation_replayed_operations=REMOTE_COUPLED_CONTINUATION_REPLAYED_OPERATIONS,
        expected_continuation_checked_relation_families=REMOTE_COUPLED_CONTINUATION_CHECKED_RELATION_FAMILIES,
        expected_continuation_checked_obligation_families=REMOTE_COUPLED_CONTINUATION_CHECKED_OBLIGATION_FAMILIES,
        expected_continuation_unchecked_obligation_families=REMOTE_COUPLED_CONTINUATION_UNCHECKED_OBLIGATION_FAMILIES,
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="tetra_plus",
        smiles="[C@H](F)(Cl)Br",
        extraction_profile="specified_stereo_closure",
        extraction_options=_SPECIFIED_STEREO_EXTRACTION,
        expected="accepted",
        support_surface="specified_tetrahedral",
        expected_support_count=6,
        expected_completion_count=6,
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_support_digest="216234e0ae01eef57744222590d56573b8e0c9f92e27dac0653b0372db4dae14",
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="tetra_minus",
        smiles="[C@@H](F)(Cl)Br",
        extraction_profile="specified_stereo_closure",
        extraction_options=_SPECIFIED_STEREO_EXTRACTION,
        expected="accepted",
        support_surface="specified_tetrahedral",
        expected_support_count=6,
        expected_completion_count=6,
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_support_digest="61c45f124f99413fb8d8e32612acc7a9c027fc6d372c133cb7a6b9b22585035f",
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="directional_opposite",
        smiles="F/C=C/Cl",
        extraction_profile="specified_stereo_closure",
        extraction_options=_SPECIFIED_STEREO_EXTRACTION,
        expected="accepted",
        support_surface="specified_directional_acyclic_implicit_h",
        expected_support_count=2,
        expected_completion_count=2,
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_support_digest="3f8f9edb2af9ff8964fa04e8ba6b8374177e773cceea2f1959cc27026bed7595",
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="directional_together",
        smiles="F/C=C\\Cl",
        extraction_profile="specified_stereo_closure",
        extraction_options=_SPECIFIED_STEREO_EXTRACTION,
        expected="accepted",
        support_surface="specified_directional_acyclic_implicit_h",
        expected_support_count=2,
        expected_completion_count=2,
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_support_digest="a5ad275c56e9dfc9530d7985fc85428997509701c95e0c2f1249a01a9d103fd8",
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="disconnected_cc_oxygen",
        smiles="CC.O",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="disconnected_fixed_order",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="c496d6252cbc6b43f8c55f0e55236a819b63685c7daf27d3886efb521bb938f4",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        expected_rdkit_audit_version_pinned=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=DISCONNECTED_OFFLINE_RELATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="disconnected_oxygen_cc",
        smiles="O.CC",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="disconnected_fixed_order",
        rooted_at_atom=1,
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="e8a7fe0505c836a927826a8adbc6537301bedd7f999552116c84a02d4e237d14",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        expected_rdkit_audit_version_pinned=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=DISCONNECTED_OFFLINE_RELATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="disconnected_duplicate_ethanes",
        smiles="CC.CC",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="disconnected_fixed_order",
        expected_support_count=1,
        expected_completion_count=2,
        expected_support_digest="7f58112ef003c228917c772afc45ce6090908fba07cc7104692a7344228a7c9b",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        expected_rdkit_audit_version_pinned=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=DISCONNECTED_OFFLINE_RELATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="disconnected_ring_oxygen",
        smiles="C1CC1.O",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="disconnected_fixed_order",
        expected_support_count=1,
        expected_completion_count=2,
        expected_support_digest="45163fc5fa812e667d8989f5ddcb7bf486ca4df0f1c80634397015b6472cc144",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        expected_rdkit_audit_version_pinned=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=DISCONNECTED_OFFLINE_RELATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="disconnected_ammonium_cyanide",
        smiles="[NH4+].C#N",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="disconnected_fixed_order",
        expected_support_count=2,
        expected_completion_count=2,
        expected_support_digest="4b55dc94da4ae4cfd3eaec167320cc374ef9caec3ef4ff287e2eab7b9cd11d82",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        expected_rdkit_audit_version_pinned=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=DISCONNECTED_OFFLINE_RELATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="disconnected_tetra_oxygen",
        smiles="[C@H](F)(Cl)Br.O",
        extraction_profile="specified_stereo_closure",
        extraction_options=_SPECIFIED_STEREO_EXTRACTION,
        expected="accepted",
        support_surface="disconnected_fixed_order",
        expected_support_count=6,
        expected_completion_count=6,
        expected_support_digest="55227adff1bf5af672a91ff730e73e2aa954c978bd6f9cbd9593f659182a50f5",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        expected_rdkit_audit_version_pinned=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=DISCONNECTED_OFFLINE_RELATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="disconnected_directional_oxygen",
        smiles="F/C=C/Cl.O",
        extraction_profile="specified_stereo_closure",
        extraction_options=_SPECIFIED_STEREO_EXTRACTION,
        expected="accepted",
        support_surface="disconnected_fixed_order",
        expected_support_count=2,
        expected_completion_count=2,
        expected_support_digest="332671b292810b0434c3678f05b542ea3c35be6f18ee1f20209d23b59cbd013f",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        expected_rdkit_audit_version_pinned=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_relation_families=DISCONNECTED_OFFLINE_RELATION_FAMILIES,
    ),
    _accepted_aromatic_case(
        name="aromatic_benzene",
        smiles="c1ccccc1",
        support_surface="aromatic_homocycle",
        support_count=1,
        completion_count=2,
        support_digest="226af40c047f4e9f24f5c075b5cb84d44fbe96d5c0b60ae8d87552a477fd1990",
    ),
    _accepted_aromatic_case(
        name="aromatic_pyridine",
        smiles="n1ccccc1",
        support_surface="aromatic_heterocycle",
        support_count=1,
        completion_count=2,
        support_digest="661ae93b36570c6b2ee32fd0221d74b9227731a0c0fdd9f2aa77ce5e3bf8a1a7",
    ),
    _accepted_aromatic_case(
        name="aromatic_furan",
        smiles="c1occc1",
        support_surface="aromatic_heterocycle",
        support_count=2,
        completion_count=2,
        support_digest="804c1bbdde3d104e192df9c348cc9718cef782236a1e53b3152e299d2351d496",
    ),
    _accepted_aromatic_case(
        name="aromatic_thiophene",
        smiles="c1sccc1",
        support_surface="aromatic_heterocycle",
        support_count=2,
        completion_count=2,
        support_digest="e1ed422e051f2cd58b0badd0271d63ea88a0069a7ad0ac7a3595e1d1f9590e2a",
    ),
    _accepted_aromatic_case(
        name="aromatic_naphthalene",
        smiles="c1ccc2ccccc2c1",
        support_surface="fused_aromatic",
        support_count=6,
        completion_count=6,
        support_digest="77bca9da5f7996678315e2cc687dc1286d2a31f8971f671eae36bb615932627c",
    ),
    _accepted_aromatic_case(
        name="aromatic_toluene",
        smiles="Cc1ccccc1",
        support_surface="aromatic_substitution",
        support_count=1,
        completion_count=2,
        support_digest="f443887e18b3a8b7abd9d4361980c0765c68c34ef03017967153e02f5fbae315",
    ),
    _accepted_aromatic_case(
        name="aromatic_biphenyl",
        smiles="c1ccccc1-c1ccccc1",
        support_surface="aromatic_single_bridge",
        support_count=3,
        completion_count=6,
        support_digest="5409e73cdaec32ad944918ee327c941ba33c227f37bceb10160327c3872e9396",
    ),
    _accepted_aromatic_case(
        name="aromatic_disconnected_benzene",
        smiles="c1ccccc1.O",
        support_surface="disconnected_aromatic",
        support_count=1,
        completion_count=2,
        support_digest="598ab02d6998a35fec5e8865881cb3d2756cacec891ef260a317f55e2d8c0e96",
        disconnected=True,
    ),
    DefaultWriterCapabilityCase(
        name="aromatic_bracketed_nh_boundary",
        smiles="[nH]1cccc1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        qualification_authority=None,
        support_surface="unsupported_aromatic_bracketed_hydrogen",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="[nH] atoms are unsupported",
    ),
    DefaultWriterCapabilityCase(
        name="aromatic_boron_boundary",
        smiles="b1ccccc1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        qualification_authority=None,
        support_surface="unsupported_aromatic_boron",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="aromatic spelling is unsupported for 'B'",
    ),
    DefaultWriterCapabilityCase(
        name="aromatic_phosphorus_boundary",
        smiles="p1ccccc1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        qualification_authority=None,
        support_surface="unsupported_aromatic_phosphorus",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="aromatic spelling is unsupported for 'P'",
    ),
    DefaultWriterCapabilityCase(
        name="aromatic_atom_map_boundary",
        smiles="c1cc[c:1]cc1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        qualification_authority=None,
        support_surface="unsupported_aromatic_atom_map",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="atom-mapped ordinary ingestion is unsupported",
    ),
    DefaultWriterCapabilityCase(
        name="charged_isotope_methyl",
        smiles="[13CH3+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        qualification_authority=None,
        support_surface="unsupported_charged_isotope",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="isotopic atoms are unsupported",
        expected_rdkit_audit_version_pinned=True,
    ),
    DefaultWriterCapabilityCase(
        name="oxygen_positive_charge",
        smiles="[O+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        qualification_authority=None,
        support_surface="unsupported_positive_oxygen_charge",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="charged atoms are unsupported",
        expected_rdkit_audit_version_pinned=True,
    ),
    DefaultWriterCapabilityCase(
        name="nitrogen_negative_charge",
        smiles="[NH2-]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        qualification_authority=None,
        support_surface="unsupported_negative_nitrogen_charge",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="charged atoms are unsupported",
        expected_rdkit_audit_version_pinned=True,
    ),
    DefaultWriterCapabilityCase(
        name="oxygen_charged_isotope",
        smiles="[18OH-]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        qualification_authority=None,
        support_surface="unsupported_charged_oxygen_isotope",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="isotopic atoms are unsupported",
        expected_rdkit_audit_version_pinned=True,
    ),
    DefaultWriterCapabilityCase(
        name="cyclopropene_potential_directional_boundary",
        smiles="C1=CC1",
        extraction_profile="with_potential_sites",
        extraction_options=_POTENTIAL_STEREO_EXTRACTION,
        expected="blocked",
        qualification_authority=None,
        support_surface="unsupported_potential_directional_non_neighbor",
        blocker_phase="frontier",
        blocker_kind="unsupported_directional_non_neighbor_ligand",
        blocker_operation="directional carrier-mark restriction",
    ),
)


ACCEPTED_DEFAULT_WRITER_CAPABILITY_CASES = tuple(
    item for item in DEFAULT_WRITER_CAPABILITY_CASES if item.expected == "accepted"
)
BLOCKED_DEFAULT_WRITER_CAPABILITY_CASES = tuple(
    item for item in DEFAULT_WRITER_CAPABILITY_CASES if item.expected == "blocked"
)


__all__ = (
    "ACCEPTED_DEFAULT_WRITER_CAPABILITY_CASES",
    "BLOCKED_DEFAULT_WRITER_CAPABILITY_CASES",
    "DEFAULT_OFFLINE_OBJECT_KINDS",
    "DEFAULT_OFFLINE_RELATION_FAMILIES",
    "DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS",
    "DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES",
    "DEFAULT_WRITER_CAPABILITY_CASES",
    "DefaultWriterCapabilityCase",
    "QualificationAuthority",
    "REMOTE_COUPLED_CONTINUATION_REPLAYED_OPERATIONS",
    "REMOTE_COUPLED_CONTINUATION_CHECKED_RELATION_FAMILIES",
    "REMOTE_COUPLED_CONTINUATION_CHECKED_OBLIGATION_FAMILIES",
    "REMOTE_COUPLED_CONTINUATION_UNCHECKED_OBLIGATION_FAMILIES",
)
