"""Declared default ordinary writer capability ledger for South Star tests."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from grimace._south_star1.errors import SouthStarErrorKind
from grimace._south_star1.rdkit_adapter import RdkitOrdinaryExtractionOptions


_GRAPH_EXTRACTION = RdkitOrdinaryExtractionOptions(include_potential_sites=False)
_POTENTIAL_STEREO_EXTRACTION = RdkitOrdinaryExtractionOptions(
    include_potential_sites=True,
)
_SPECIFIED_STEREO_EXTRACTION = RdkitOrdinaryExtractionOptions(
    include_potential_sites=True,
    stereo_site_discovery_mode="specified_closure",
)

DEFAULT_OFFLINE_RELATION_FAMILIES = (
    "branch_projection_identity",
    "count_dag_arithmetic",
    "graph_ring_branch_delta",
    "local_branch_successor_evidence",
    "residual_stereo_obligation_classification",
    "support_image_coverage",
    "support_string_replay_path",
    "terminal_support_identity",
)

DEFAULT_OFFLINE_OBJECT_KINDS = (
    "branch_support",
    "count_dag",
    "count_envelope",
    "frontier_product",
    "replay_path",
    "source_snapshot",
    "support_image",
    "support_image_coverage",
    "support_string",
    "terminal_projection",
    "terminal_support",
    "text_projection",
)

DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS: tuple[str, ...] = ()
DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES: tuple[str, ...] = ()

DEFAULT_ACCEPTED_AGREEMENT_TIERS = {
    "expected_live_frontier_agreement_complete": True,
    "expected_live_count_agreement_complete": True,
    "expected_snapshot_resume_agreement_complete": True,
    "expected_continuation_asset_complete": True,
    "expected_rust_runtime_agreement_complete": True,
    "expected_continuation_snapshot_resume_complete": True,
    "expected_lazy_branch_proof_complete": True,
    "expected_lazy_terminal_proof_complete": True,
}


@dataclass(frozen=True, slots=True)
class DefaultWriterCapabilityCase:
    name: str
    smiles: str
    extraction_profile: Literal[
        "graph_no_potential_sites",
        "specified_stereo_closure",
        "with_potential_sites",
    ]
    extraction_options: RdkitOrdinaryExtractionOptions
    expected: Literal["accepted", "blocked"]
    support_surface: str
    expected_support_count: int | None = None
    expected_completion_count: int | None = None
    blocker_phase: Literal["preparation", "frontier"] | None = None
    blocker_kind: str | None = None
    blocker_operation: str | None = None
    blocker_error_kind: SouthStarErrorKind | None = None
    blocker_message_contains: str | None = None
    expected_structural_artifact: bool = False
    expected_live_artifact_verifier: bool = False
    expected_facts_bound_verifier: bool = False
    expected_offline_replay_complete: bool = False
    expected_live_frontier_agreement_complete: bool = False
    expected_live_count_agreement_complete: bool = False
    expected_snapshot_resume_agreement_complete: bool = False
    expected_continuation_asset_complete: bool = False
    expected_rust_runtime_agreement_complete: bool = False
    expected_continuation_snapshot_resume_complete: bool = False
    expected_lazy_branch_proof_complete: bool = False
    expected_lazy_terminal_proof_complete: bool = False
    expected_support_digest: str | None = None
    expected_rdkit_audit_version_pinned: bool = False
    expected_offline_object_kinds: tuple[str, ...] = ()
    expected_offline_unchecked_object_kinds: tuple[str, ...] = ()
    expected_offline_relation_families: tuple[str, ...] = ()
    expected_offline_unchecked_obligation_families: tuple[str, ...] = ()


DEFAULT_WRITER_CAPABILITY_CASES = (
    DefaultWriterCapabilityCase(
        name="ethanol",
        smiles="CCO",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="acyclic_graph",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="158da5592968f7fdda045dd00edb2fa2efa66ce320dc29cb4c95c1a03a918a7d",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="branched_alcohol",
        smiles="CC(C)O",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="branched_graph",
        expected_support_count=2,
        expected_completion_count=2,
        expected_support_digest="b8b02b860ced5a1bbf327d50859b9ce3b7565a9d1a7bce8d0165c8178a7112b8",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="cyclopropane",
        smiles="C1CC1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="single_ring_closure",
        expected_support_count=1,
        expected_completion_count=2,
        expected_support_digest="312276a2ad4cdc05fe8ad6b024ada99af6fb832b8d02414ec769ae85b286decd",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="cyclobutane",
        smiles="C1CCC1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="single_ring_closure",
        expected_support_count=1,
        expected_completion_count=2,
        expected_support_digest="a6905e29e645f4d04479ce90a41a3bb276baba14bba3fc36d6f83e2dc61d6d17",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="cyclopropene_double_closure",
        smiles="C1=CC1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="non_single_ring_closure_double",
        expected_support_count=3,
        expected_completion_count=3,
        expected_support_digest="8e6083dc9807cd94031fbae1a9cf9e7d85efc7f8450a017fd22e95c3a46cf836",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="cyclopropyne_triple_closure",
        smiles="C1#CC1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="non_single_ring_closure_triple",
        expected_support_count=3,
        expected_completion_count=3,
        expected_support_digest="7aa9e14f4a2340677cbb14f2281aac8e4fed116870899c72cd5b910e1d7a4695",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="branched_cyclobutane",
        smiles="C1CC(C)C1",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="branched_ring",
        expected_support_count=2,
        expected_completion_count=4,
        expected_support_digest="ea98a1e3ebec1a69635db0d3bafb2df37ac59eb78aa5660602cf2c4d8150966d",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="nitrogen_cation",
        smiles="[N+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="3e0dafe1d624e7e97c5d7b691949ffa7c22306a7e95bf47680d71550d0292b0d",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="iminium_hydrogen_cation",
        smiles="[NH+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="8f26d7dc968fc63177d76b06157a835c75480cd7b0f4271c6a77b1dfcc9b98b6",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="amino_cation",
        smiles="[NH2+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="4da0d2d64ad0649366cfa81a3994fec9589bc4e249a806707784d704d956c591",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="ammonia_cation",
        smiles="[NH3+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="ae9db23fc1587d0c8634d031ebdfaafdea0a8a3e6af1dae1183f2c71c67b1391",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="ammonium_charge",
        smiles="[NH4+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="7ecb28fb094c1b9013610ebb987e39e8b76e55bfdb38af53ab682bd2f1467719",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="oxide_anion",
        smiles="[O-]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="bfa4c3013b04f7db71e834923cce839e0499c9d702fb2e704fd4e13c9ad189bb",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="hydroxide_anion",
        smiles="[OH-]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_bracket_charge",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="4ce4a6fbb41bf1f00917e46cb5164119c2a52990305cd4888ff8a7fc621df10f",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="isotopic_methane",
        smiles="[13CH4]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="accepted",
        support_surface="simple_isotope_bracket_atom",
        expected_support_count=1,
        expected_completion_count=1,
        expected_support_digest="28b7468eeb6985fb4cb5d56ab6f665c9d3fb65d63519f625668f797d18b61242",
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="tetra_plus",
        smiles="[C@H](F)(Cl)Br",
        extraction_profile="specified_stereo_closure",
        extraction_options=_SPECIFIED_STEREO_EXTRACTION,
        expected="accepted",
        support_surface="specified_tetrahedral",
        expected_support_count=6,
        expected_completion_count=6,
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_support_digest="216234e0ae01eef57744222590d56573b8e0c9f92e27dac0653b0372db4dae14",
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="tetra_minus",
        smiles="[C@@H](F)(Cl)Br",
        extraction_profile="specified_stereo_closure",
        extraction_options=_SPECIFIED_STEREO_EXTRACTION,
        expected="accepted",
        support_surface="specified_tetrahedral",
        expected_support_count=6,
        expected_completion_count=6,
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_support_digest="61c45f124f99413fb8d8e32612acc7a9c027fc6d372c133cb7a6b9b22585035f",
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="directional_opposite",
        smiles="F/C=C/Cl",
        extraction_profile="specified_stereo_closure",
        extraction_options=_SPECIFIED_STEREO_EXTRACTION,
        expected="accepted",
        support_surface="specified_directional_acyclic_implicit_h",
        expected_support_count=2,
        expected_completion_count=2,
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_support_digest="3f8f9edb2af9ff8964fa04e8ba6b8374177e773cceea2f1959cc27026bed7595",
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="directional_together",
        smiles="F/C=C\\Cl",
        extraction_profile="specified_stereo_closure",
        extraction_options=_SPECIFIED_STEREO_EXTRACTION,
        expected="accepted",
        support_surface="specified_directional_acyclic_implicit_h",
        expected_support_count=2,
        expected_completion_count=2,
        expected_structural_artifact=True,
        expected_live_artifact_verifier=True,
        expected_facts_bound_verifier=True,
        expected_offline_replay_complete=True,
        **DEFAULT_ACCEPTED_AGREEMENT_TIERS,
        expected_support_digest="a5ad275c56e9dfc9530d7985fc85428997509701c95e0c2f1249a01a9d103fd8",
        expected_rdkit_audit_version_pinned=True,
        expected_offline_object_kinds=DEFAULT_OFFLINE_OBJECT_KINDS,
        expected_offline_unchecked_object_kinds=DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS,
        expected_offline_relation_families=DEFAULT_OFFLINE_RELATION_FAMILIES,
        expected_offline_unchecked_obligation_families=DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES,
    ),
    DefaultWriterCapabilityCase(
        name="charged_isotope_methyl",
        smiles="[13CH3+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        support_surface="unsupported_charged_isotope",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="isotopic atoms are unsupported",
        expected_rdkit_audit_version_pinned=True,
    ),
    DefaultWriterCapabilityCase(
        name="oxygen_positive_charge",
        smiles="[O+]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        support_surface="unsupported_positive_oxygen_charge",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="charged atoms are unsupported",
        expected_rdkit_audit_version_pinned=True,
    ),
    DefaultWriterCapabilityCase(
        name="nitrogen_negative_charge",
        smiles="[NH2-]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        support_surface="unsupported_negative_nitrogen_charge",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="charged atoms are unsupported",
        expected_rdkit_audit_version_pinned=True,
    ),
    DefaultWriterCapabilityCase(
        name="oxygen_charged_isotope",
        smiles="[18OH-]",
        extraction_profile="graph_no_potential_sites",
        extraction_options=_GRAPH_EXTRACTION,
        expected="blocked",
        support_surface="unsupported_charged_oxygen_isotope",
        blocker_phase="preparation",
        blocker_kind="unsupported_atom",
        blocker_error_kind=SouthStarErrorKind.UNSUPPORTED_ATOM,
        blocker_message_contains="isotopic atoms are unsupported",
        expected_rdkit_audit_version_pinned=True,
    ),
    DefaultWriterCapabilityCase(
        name="cyclopropene_potential_directional_boundary",
        smiles="C1=CC1",
        extraction_profile="with_potential_sites",
        extraction_options=_POTENTIAL_STEREO_EXTRACTION,
        expected="blocked",
        support_surface="unsupported_potential_directional_non_neighbor",
        blocker_phase="frontier",
        blocker_kind="unsupported_directional_non_neighbor_ligand",
        blocker_operation="directional carrier-mark restriction",
    ),
)


ACCEPTED_DEFAULT_WRITER_CAPABILITY_CASES = tuple(
    item for item in DEFAULT_WRITER_CAPABILITY_CASES if item.expected == "accepted"
)
BLOCKED_DEFAULT_WRITER_CAPABILITY_CASES = tuple(
    item for item in DEFAULT_WRITER_CAPABILITY_CASES if item.expected == "blocked"
)


__all__ = (
    "ACCEPTED_DEFAULT_WRITER_CAPABILITY_CASES",
    "BLOCKED_DEFAULT_WRITER_CAPABILITY_CASES",
    "DEFAULT_OFFLINE_OBJECT_KINDS",
    "DEFAULT_OFFLINE_RELATION_FAMILIES",
    "DEFAULT_OFFLINE_UNCHECKED_OBJECT_KINDS",
    "DEFAULT_OFFLINE_UNCHECKED_OBLIGATION_FAMILIES",
    "DEFAULT_WRITER_CAPABILITY_CASES",
    "DefaultWriterCapabilityCase",
)
