from typing import Any


class PreparedSmilesGraph:
    def __init__(self, data: object, /) -> None: ...

    @property
    def schema_version(self) -> int: ...

    @property
    def surface_kind(self) -> str: ...

    @property
    def policy_name(self) -> str: ...

    @property
    def policy_digest(self) -> str: ...

    @property
    def rdkit_version(self) -> str: ...

    @property
    def identity_smiles(self) -> str: ...

    @property
    def atom_count(self) -> int: ...

    @property
    def bond_count(self) -> int: ...

    @property
    def atom_tokens(self) -> list[str]: ...

    @property
    def bond_dirs(self) -> list[str]: ...

    def neighbors_of(self, atom_idx: int, /) -> list[int]: ...
    def bond_token(self, begin_idx: int, end_idx: int, /) -> str: ...
    def matches_writer_flags(
        self,
        *,
        isomeric_smiles: bool,
        kekule_smiles: bool,
        all_bonds_explicit: bool,
        all_hs_explicit: bool,
        ignore_atom_map_numbers: bool,
    ) -> bool: ...
    def token_inventory_superset(self, root_idx: int, /) -> list[str]: ...
    def validate_policy(self, policy_name: str, policy_digest: str, /) -> None: ...
    def enumerate_rooted_connected_nonstereo_support(self, root_idx: int, /) -> list[str]: ...
    def enumerate_rooted_connected_stereo_support(self, root_idx: int, /) -> list[str]: ...
    def to_dict(self) -> dict[str, Any]: ...


class PreparedMol:
    @staticmethod
    def from_bytes(data: bytes, /) -> "PreparedMol": ...

    def to_bytes(self) -> bytes: ...
    def matches_writer_flags(
        self,
        *,
        isomeric_smiles: bool,
        kekule_smiles: bool,
        all_bonds_explicit: bool,
        all_hs_explicit: bool,
        ignore_atom_map_numbers: bool,
    ) -> bool: ...
    def fragment_count(self) -> int: ...
    def atom_count(self) -> int: ...
    def rooted_fragments(
        self,
        rooted_at_atom: int | None,
        /,
    ) -> list[tuple[PreparedSmilesGraph, int | None]]: ...


class _SplitMix64Sampler:
    def __init__(self, seed: int, /) -> None: ...
    def uniform_index(self, len: int, /) -> int: ...
    def weighted_index(self, weights: list[int], /) -> int: ...


class RootedConnectedNonStereoWalkerState:
    @property
    def prefix(self) -> str: ...


class RootedConnectedNonStereoWalker:
    def __init__(self, graph: object, root_idx: int, /) -> None: ...

    @property
    def root_idx(self) -> int: ...

    def initial_state(self) -> RootedConnectedNonStereoWalkerState: ...
    def next_token_support(
        self,
        state: RootedConnectedNonStereoWalkerState,
        /,
    ) -> list[str]: ...
    def next_choice_texts(
        self,
        state: RootedConnectedNonStereoWalkerState,
        /,
    ) -> list[str]: ...
    def advance_token(
        self,
        state: RootedConnectedNonStereoWalkerState,
        chosen_token: str,
        /,
    ) -> RootedConnectedNonStereoWalkerState: ...
    def advance_choice(
        self,
        state: RootedConnectedNonStereoWalkerState,
        chosen_idx: int,
        /,
    ) -> RootedConnectedNonStereoWalkerState: ...
    def is_terminal(self, state: RootedConnectedNonStereoWalkerState, /) -> bool: ...
    def enumerate_support(self) -> list[str]: ...


class RootedConnectedNonStereoDecoder:
    def __init__(self, graph: object, root_idx: int, /) -> None: ...
    def cache_key(self) -> str: ...
    def next_token_support(self) -> list[str]: ...
    def next_choice_texts(self) -> list[str]: ...
    def advance_token(self, chosen_token: str, /) -> None: ...
    def advance_choice(self, chosen_idx: int, /) -> None: ...
    def prefix(self) -> str: ...
    def is_terminal(self) -> bool: ...
    def copy(self) -> "RootedConnectedNonStereoDecoder": ...


class RootedConnectedStereoWalkerState:
    @property
    def prefix(self) -> str: ...


class RootedConnectedStereoWalker:
    def __init__(self, graph: object, root_idx: int, /) -> None: ...

    @property
    def root_idx(self) -> int: ...

    def initial_state(self) -> RootedConnectedStereoWalkerState: ...
    def next_token_support(
        self,
        state: RootedConnectedStereoWalkerState,
        /,
    ) -> list[str]: ...
    def next_choice_texts(
        self,
        state: RootedConnectedStereoWalkerState,
        /,
    ) -> list[str]: ...
    def advance_token(
        self,
        state: RootedConnectedStereoWalkerState,
        chosen_token: str,
        /,
    ) -> RootedConnectedStereoWalkerState: ...
    def advance_choice(
        self,
        state: RootedConnectedStereoWalkerState,
        chosen_idx: int,
        /,
    ) -> RootedConnectedStereoWalkerState: ...
    def is_terminal(self, state: RootedConnectedStereoWalkerState, /) -> bool: ...
    def enumerate_support(self) -> list[str]: ...


class RootedConnectedStereoDecoder:
    def __init__(self, graph: object, root_idx: int, /) -> None: ...
    def cache_key(self) -> str: ...
    def next_token_support(self) -> list[str]: ...
    def next_choice_texts(self) -> list[str]: ...
    def advance_token(self, chosen_token: str, /) -> None: ...
    def advance_choice(self, chosen_idx: int, /) -> None: ...
    def prefix(self) -> str: ...
    def is_terminal(self) -> bool: ...
    def copy(self) -> "RootedConnectedStereoDecoder": ...


def prepared_smiles_graph_schema_version() -> int: ...
def mol_to_smiles_support(
    graph: object,
    root_idx: int,
    isomeric_smiles: bool,
    /,
) -> list[str]: ...
