from typing import Any


class WriterContinuationRustCursor:
    @property
    def node_id(self) -> int: ...
    @property
    def completion_scale(self) -> int: ...
    def copy(self) -> "WriterContinuationRustCursor": ...


class WriterContinuationRustChoice:
    @property
    def text(self) -> str: ...
    @property
    def immediate_multiplicity(self) -> int: ...
    @property
    def support_count(self) -> int: ...
    @property
    def completion_count(self) -> int: ...
    @property
    def next_cursor(self) -> WriterContinuationRustCursor: ...


class WriterContinuationRustProbability:
    @property
    def text(self) -> str | None: ...
    @property
    def numerator(self) -> int: ...
    @property
    def denominator(self) -> int: ...


class WriterContinuationRustCore:
    @property
    def manifest_digest(self) -> str: ...
    @property
    def node_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def resident_bytes(self) -> int: ...
    def root_cursor(self) -> WriterContinuationRustCursor: ...
    def cursor(self, node_id: int, completion_scale: int) -> WriterContinuationRustCursor: ...
    def choices(self, cursor: WriterContinuationRustCursor) -> list[WriterContinuationRustChoice]: ...
    def advance(self, cursor: WriterContinuationRustCursor, emitted_text: str) -> WriterContinuationRustCursor: ...
    def is_terminal(self, cursor: WriterContinuationRustCursor) -> bool: ...
    def support_count(self, cursor: WriterContinuationRustCursor) -> int: ...
    def completion_count(self, cursor: WriterContinuationRustCursor) -> int: ...
    def terminal_completion_count(self, cursor: WriterContinuationRustCursor) -> int: ...
    def probabilities(self, cursor: WriterContinuationRustCursor) -> list[WriterContinuationRustProbability]: ...


def _writer_continuation_rust_core_from_verified_terms(
    manifest_digest: str,
    root_node_id: int,
    root_scale: int,
    nodes: object,
    /,
) -> WriterContinuationRustCore: ...


class PreparedSmilesGraph:
    def __init__(self, data: object, /) -> None: ...

    @property
    def schema_version(self) -> int: ...

    @property
    def surface_kind(self) -> str: ...

    @property
    def policy_name(self) -> str: ...

    @property
    def policy_digest(self) -> str: ...

    @property
    def rdkit_version(self) -> str: ...

    @property
    def identity_smiles(self) -> str: ...

    @property
    def atom_count(self) -> int: ...

    @property
    def bond_count(self) -> int: ...

    @property
    def atom_tokens(self) -> list[str]: ...

    @property
    def bond_dirs(self) -> list[str]: ...

    def neighbors_of(self, atom_idx: int, /) -> list[int]: ...
    def bond_token(self, begin_idx: int, end_idx: int, /) -> str: ...
    def validate_policy(self, policy_name: str, policy_digest: str, /) -> None: ...
    def enumerate_rooted_connected_nonstereo_support(self, root_idx: int, /) -> list[str]: ...
    def enumerate_rooted_connected_stereo_support(self, root_idx: int, /) -> list[str]: ...
    def to_dict(self) -> dict[str, Any]: ...


class RootedConnectedNonStereoWalkerState:
    @property
    def prefix(self) -> str: ...


class RootedConnectedNonStereoWalker:
    def __init__(self, graph: object, root_idx: int, /) -> None: ...

    @property
    def root_idx(self) -> int: ...

    def initial_state(self) -> RootedConnectedNonStereoWalkerState: ...
    def next_token_support(
        self,
        state: RootedConnectedNonStereoWalkerState,
        /,
    ) -> list[str]: ...
    def next_choice_texts(
        self,
        state: RootedConnectedNonStereoWalkerState,
        /,
    ) -> list[str]: ...
    def advance_token(
        self,
        state: RootedConnectedNonStereoWalkerState,
        chosen_token: str,
        /,
    ) -> RootedConnectedNonStereoWalkerState: ...
    def advance_choice(
        self,
        state: RootedConnectedNonStereoWalkerState,
        chosen_idx: int,
        /,
    ) -> RootedConnectedNonStereoWalkerState: ...
    def is_terminal(self, state: RootedConnectedNonStereoWalkerState, /) -> bool: ...
    def enumerate_support(self) -> list[str]: ...


class RootedConnectedNonStereoDecoder:
    def __init__(self, graph: object, root_idx: int, /) -> None: ...
    def cache_key(self) -> str: ...
    def next_token_support(self) -> list[str]: ...
    def next_choice_texts(self) -> list[str]: ...
    def advance_token(self, chosen_token: str, /) -> None: ...
    def advance_choice(self, chosen_idx: int, /) -> None: ...
    def prefix(self) -> str: ...
    def is_terminal(self) -> bool: ...
    def copy(self) -> "RootedConnectedNonStereoDecoder": ...


class RootedConnectedStereoWalkerState:
    @property
    def prefix(self) -> str: ...


class RootedConnectedStereoWalker:
    def __init__(self, graph: object, root_idx: int, /) -> None: ...

    @property
    def root_idx(self) -> int: ...

    def initial_state(self) -> RootedConnectedStereoWalkerState: ...
    def next_token_support(
        self,
        state: RootedConnectedStereoWalkerState,
        /,
    ) -> list[str]: ...
    def next_choice_texts(
        self,
        state: RootedConnectedStereoWalkerState,
        /,
    ) -> list[str]: ...
    def advance_token(
        self,
        state: RootedConnectedStereoWalkerState,
        chosen_token: str,
        /,
    ) -> RootedConnectedStereoWalkerState: ...
    def advance_choice(
        self,
        state: RootedConnectedStereoWalkerState,
        chosen_idx: int,
        /,
    ) -> RootedConnectedStereoWalkerState: ...
    def is_terminal(self, state: RootedConnectedStereoWalkerState, /) -> bool: ...
    def enumerate_support(self) -> list[str]: ...


class RootedConnectedStereoDecoder:
    def __init__(self, graph: object, root_idx: int, /) -> None: ...
    def cache_key(self) -> str: ...
    def next_token_support(self) -> list[str]: ...
    def next_choice_texts(self) -> list[str]: ...
    def advance_token(self, chosen_token: str, /) -> None: ...
    def advance_choice(self, chosen_idx: int, /) -> None: ...
    def prefix(self) -> str: ...
    def is_terminal(self) -> bool: ...
    def copy(self) -> "RootedConnectedStereoDecoder": ...


def prepared_smiles_graph_schema_version() -> int: ...
def mol_to_smiles_support(
    graph: object,
    root_idx: int,
    isomeric_smiles: bool,
    /,
) -> list[str]: ...
